{{- if and .Values.seed.enabled (not .Values.seed.existingAdminSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-kuma.fullname" . }}-seed
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.seed.adminUsername | quote }}
  password: {{ .Values.seed.adminPassword | quote }}
{{- end }}
